[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

# [profile.dependencies]
# forge-std = { git = "https://github.com/foundry-rs/forge-std" }
# openzeppelin-contracts-upgradeable = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable.git" }
# openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git"}


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
